### ISSUE TITLE
El ejercicio 30

### ISSUE THREAD

**Issue by FacundoRauber** [FacundoRauber/fullstack2022#3]

**Comment by FacundoRauber** [comment]
podes revisar en tal url la respuesta
selec * from respuesta

**Comment by JorgeEduardoFerreira** [comment]
Buenas, Respecto al Ejercicio 30, se vio la solucion en clases, la verdad como no habia llegado no entendí mucho, realize una consulta, me trae los datos pero como no hay Pedidos en el mismo dia no estoy seguró si es correcto, me podrian dar una mano con eso, les dejo el codigo para ver si es correcto.
 ```
    select c.id, c.nombre, c.apellido, p.fecha, max(p.cantidad)
    from ventas.clientes as c
    inner join ventas.pedidos as p
    on c.id=p.id_cliente
    group by fecha;
```

**Comment by JorgeEduardoFerreira** [comment]
Despues de Buscarle la vuelta conseguí este scrip y creo q esta correcto. 
```
select distinct c.id as 'ID cliente', c.nombre, c.apellido, p.fecha, max(p.cantidad) as 'Cantidad MAX del día'
	from ventas.clientes as c
    inner join ventas.pedidos as p
    on c.id=p.id_cliente
    group by p.fecha, p.id_cliente
    order by p.fecha desc;
```

**Comment by FacundoRauber** [comment]
Son 20 pedidos, 2 son del mismo cliente. Entonces en la lista deben haber 19 pedidos como muestra en el ultimo script.
