### ISSUE TITLE
TP 6 Ejercicio 1 punto 14

### ISSUE THREAD

**Issue by fgabrielmartinez** [FacundoRauber/fullstack2022#4]
14. Borrar lógicamente (UPDATE de la columna estado):
● 2 movimientos que fueron cargados mal
● un pais que tenga al menos 3 localidades

**Comment by fgabrielmartinez** [comment]
pero en la tabla paises no tenemos columna estado. hay que crearla y luego modificarla?

**Comment by FacundoRauber** [comment]
No me di cuenta de eso, la columna de "estados" habria que agregarla a todas las tablas.
