### ISSUE TITLE
TP6 - Ejercicio 6 - columnas 'estado' en todas las tablas

### ISSUE THREAD

**Issue by capinf** [FacundoRauber/fullstack2022#5]
En todas las tablas se solicita una columna 'estado' ... La planteamos como tipo de dato BOOLEAN ? lleva predefinido los estados? El dato nace con un estado por por defecto? Por ejemplo:

``
estado BOOLEAN NOT NULL default false;
``

**Comment by FacundoRauber** [comment]
Se agrega la columna estado de tipo boolean. Cuando se realice la carga pueden cargar valores con estado en true o estado en false. Lo ideal es que tengan la mayoria de los estados en true y puede admitir nulo.
