### ISSUE TITLE
TP6 - Ejercicio 6 - tabla 'cajas' - columnas 'horainicio' & 'horacierre'

### ISSUE THREAD

**Issue by capinf** [FacundoRauber/fullstack2022#6]
En el ejercicio se solicita crear una tabla 'cajas' con las siguientes características:

> Cajas (id,horainicio(datatime),horacierre(datatime), estado, tms)

Podría explicar la naturaleza y función de la tabla? Cómo funcionarían las columnas horario inicio y cierre? Éstas permiten tener datos NULL? Por ejemplo ... insertar un dato e inicio, pero dejar nulo el dato cierre?

**Comment by FacundoRauber** [comment]
Este es un caso de ejemplo para realizar un ejercicio. Si fuera un caso real la tabla cajas se suele utilizar para hacer aperturas y cierres de caja, entonces le estaria faltando atributos y relaciones. Una relacion (a modo de ejemplo) seria la caja con los movimientos. Una o varias cajas tiene uno o varios movimientos. En ese caso habria una tabla intermedia caja_movimientos. 
Siguiendo el ejemplo de la tabla Cajas, hay 2 pradigamas o tendencias fuertes en dejar NULL o NOT NULL campos. Dejaria que en la base de datos admita NULL, lo controlaria por el backend de esta manera a la larga es mas facil mantener. Pero la vieja escuela dice que no puede ser NULL y lo controlaria por la base de datos. Cualquiera de las dos maneras se puede resolver.

**Comment by capinf** [comment]
Buenísimo ... Si justamente por la falta de atributos y relaciones confunde. Con el paradigma de dejarlo NULL resuelve la mayoría de la consulta.

Gracias @FacundoRauber por responder !!!
