### ISSUE TITLE
Tengo inconvenientes con el INSERT JSON en la columna "cosas" de la tabla parámetros, no me toma los dos últimos puntos (mysql workbench)

### ISSUE THREAD

**Issue by jrgrondona** [FacundoRauber/fullstack2022#8]

**Comment by fgabrielmartinez** [comment]
hola fíjate las comillas.. en uno de los json tiene una comilla diferente y en otro le faltan comillas. por lo menos así solucione yo

**Comment by jrgrondona** [comment]
Hola Gabriel, si si eso lo identifique lo de las comillas deferente, ese punto me cargo sin problema. Era un tema con mi sistema de workbench.
Muchísimas gracias por el aporte. Saludos !!!

**Comment by LautaroGon24** [comment]
Si, los puntos 2 y 4 tenian incovenientes los json. Así estarían corregidos:
●{"vistasPermitidas": "menuPrincipal,menuSecundario,ventas,estadisticaVentas,listaCliente","grupo": "ventas"}
●{"balancesAniosAnteriores": {"2019": {"ingreso": "7374901.93","egreso": "3732538,75"},"2020":{"ingreso": "27442665,12","egreso": "8522331,82"}
